package com.re.rikkei_bank;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.io.FileWriter;
import java.io.PrintWriter;

/**
 * Chạy file này để generate file SQL seed data với BCrypt hashes chính xác.
 * 
 * Cách chạy:
 *   Trong IntelliJ/Eclipse: Right-click → Run 'GenerateSeedSQL'
 *   Hoặc: ./gradlew bootRun sẽ tự chạy DataSeeder.java
 */
public class GenerateSeedSQL {

    public static void main(String[] args) throws Exception {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        
        // Generate hashes
        String passwordHash = encoder.encode("Admin@1234");
        String pinHash = encoder.encode("123456");
        
        String filePath = "docs/seed_data.sql";
        
        try (PrintWriter pw = new PrintWriter(new FileWriter(filePath))) {
            pw.println("-- ═══════════════════════════════════════════════════════════════════════");
            pw.println("-- RIKKEI BANK - SEED DATA");
            pw.println("-- Generated by GenerateSeedSQL.java");
            pw.println("-- ═══════════════════════════════════════════════════════════════════════");
            pw.println("-- ");
            pw.println("-- THÔNG TIN ĐĂNG NHẬP:");
            pw.println("--   Mật khẩu tất cả tài khoản: Admin@1234");
            pw.println("--   Mã PIN tất cả tài khoản:   123456");
            pw.println("-- ");
            pw.println("-- ═══════════════════════════════════════════════════════════════════════");
            pw.println("--  Username      | Role     | Account Number | Balance (VND)  | Status");
            pw.println("--  ─────────────────────────────────────────────────────────────────────");
            pw.println("--  admin         | ADMIN    | 9000000001     | 999,999,999    | ✅");
            pw.println("--  staff01       | STAFF    | 9000000002     | 50,000,000     | ✅");
            pw.println("--  staff02       | STAFF    | 9000000003     | 45,000,000     | ✅");
            pw.println("--  customer01    | CUSTOMER | 1001000001     | 75,000,000     | ✅ KYC OK");
            pw.println("--  customer02    | CUSTOMER | 1001000002     | 32,500,000     | ✅ KYC OK");
            pw.println("--  customer03    | CUSTOMER | 1001000003     | 120,000,000    | ✅ KYC OK");
            pw.println("--  customer04    | CUSTOMER | 1001000004     | 8,500,000      | ✅ KYC OK");
            pw.println("--  customer05    | CUSTOMER | 1001000005     | 15,000,000     | ⏳ KYC PENDING");
            pw.println("--  customer06    | CUSTOMER | 1001000006     | 5,000,000      | ❌ KYC REJECT");
            pw.println("--  customer07    | CUSTOMER | 1001000007     | 22,000,000     | 🔒 USER LOCKED");
            pw.println("-- ═══════════════════════════════════════════════════════════════════════");
            pw.println();
            pw.println("-- Sử dụng database rikkei_bank");
            pw.println("CREATE DATABASE IF NOT EXISTS rikkei_bank;");
            pw.println("USE rikkei_bank;");
            pw.println();
            pw.println("-- Tắt kiểm tra foreign key để INSERT thuận tiện");
            pw.println("SET FOREIGN_KEY_CHECKS = 0;");
            pw.println();
            
            // ====== ROLES ======
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- 1. ROLES (3 roles)");
            pw.println("-- ══════════════════════════════════════════");
            pw.println("TRUNCATE TABLE refresh_tokens;");
            pw.println("TRUNCATE TABLE transactions;");
            pw.println("TRUNCATE TABLE kyc_profiles;");
            pw.println("TRUNCATE TABLE accounts;");
            pw.println("TRUNCATE TABLE users;");
            pw.println("TRUNCATE TABLE roles;");
            pw.println();
            pw.println("INSERT INTO roles (id, name, description) VALUES");
            pw.println("(1, 'ROLE_ADMIN',    'Quản trị viên hệ thống - toàn quyền quản lý'),");
            pw.println("(2, 'ROLE_STAFF',    'Nhân viên ngân hàng - duyệt KYC, xem tài khoản'),");
            pw.println("(3, 'ROLE_CUSTOMER', 'Khách hàng - giao dịch, xem số dư, đổi PIN');");
            pw.println();

            // ====== USERS ======
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- 2. USERS (10 users)");
            pw.println("-- Mật khẩu tất cả: Admin@1234");
            pw.println("-- ══════════════════════════════════════════");
            String now = "NOW()";
            pw.println("INSERT INTO users (id, username, password, email, phone_number, is_active, is_kyc, role_id, created_at, updated_at) VALUES");
            pw.printf("(1,  'admin',      '%s', 'admin@rikkeibank.vn',      '0900000001', true,  true,  1, %s, %s),%n", passwordHash, now, now);
            pw.printf("(2,  'staff01',    '%s', 'staff01@rikkeibank.vn',    '0900000002', true,  true,  2, %s, %s),%n", passwordHash, now, now);
            pw.printf("(3,  'staff02',    '%s', 'staff02@rikkeibank.vn',    '0900000003', true,  true,  2, %s, %s),%n", passwordHash, now, now);
            pw.printf("(4,  'customer01', '%s', 'nguyenvanan@gmail.com',    '0912345001', true,  true,  3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(5,  'customer02', '%s', 'tranthib@gmail.com',       '0912345002', true,  true,  3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(6,  'customer03', '%s', 'lequangcuong@gmail.com',   '0912345003', true,  true,  3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(7,  'customer04', '%s', 'phamthidung@gmail.com',    '0912345004', true,  true,  3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(8,  'customer05', '%s', 'hoangvanem@gmail.com',     '0912345005', true,  false, 3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(9,  'customer06', '%s', 'dangthiphuong@gmail.com',  '0912345006', true,  false, 3, %s, %s),%n", passwordHash, now, now);
            pw.printf("(10, 'customer07', '%s', 'vothigiang@gmail.com',     '0912345007', false, false, 3, %s, %s);%n", passwordHash, now, now);
            pw.println();

            // ====== ACCOUNTS ======
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- 3. ACCOUNTS (10 accounts)");
            pw.println("-- PIN tất cả: 123456");
            pw.println("-- ══════════════════════════════════════════");
            pw.println("INSERT INTO accounts (id, account_number, balance, currency, transaction_pin, status, active, user_id, created_at, updated_at) VALUES");
            pw.printf("(1,  '9000000001', 999999999.00,  'VND', '%s', 'ACTIVE', true, 1,  %s, %s),%n", pinHash, now, now);
            pw.printf("(2,  '9000000002', 50000000.00,   'VND', '%s', 'ACTIVE', true, 2,  %s, %s),%n", pinHash, now, now);
            pw.printf("(3,  '9000000003', 45000000.00,   'VND', '%s', 'ACTIVE', true, 3,  %s, %s),%n", pinHash, now, now);
            pw.printf("(4,  '1001000001', 75000000.00,   'VND', '%s', 'ACTIVE', true, 4,  %s, %s),%n", pinHash, now, now);
            pw.printf("(5,  '1001000002', 32500000.00,   'VND', '%s', 'ACTIVE', true, 5,  %s, %s),%n", pinHash, now, now);
            pw.printf("(6,  '1001000003', 120000000.00,  'VND', '%s', 'ACTIVE', true, 6,  %s, %s),%n", pinHash, now, now);
            pw.printf("(7,  '1001000004', 8500000.00,    'VND', '%s', 'ACTIVE', true, 7,  %s, %s),%n", pinHash, now, now);
            pw.printf("(8,  '1001000005', 15000000.00,   'VND', '%s', 'ACTIVE', true, 8,  %s, %s),%n", pinHash, now, now);
            pw.printf("(9,  '1001000006', 5000000.00,    'VND', '%s', 'ACTIVE', true, 9,  %s, %s),%n", pinHash, now, now);
            pw.printf("(10, '1001000007', 22000000.00,   'VND', '%s', 'LOCKED', true, 10, %s, %s);%n", pinHash, now, now);
            pw.println();

            // ====== KYC PROFILES ======
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- 4. KYC PROFILES (7 profiles)");
            pw.println("-- ══════════════════════════════════════════");
            pw.println("INSERT INTO kyc_profiles (id, id_number, full_name, dob, gender, address, cccd_front_url, cccd_back_url, selfie_url, status, reject_reason, verified_at, user_id, created_at, updated_at) VALUES");
            pw.println("(1, '079201001001', 'Nguyễn Văn An',    '1995-03-15', 'MALE',   '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201001001_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201001001_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201001001_selfie.jpg',");
            pw.printf( "    'CONFIRM', NULL, %s, 4, %s, %s),%n", now, now, now);
            
            pw.println("(2, '079201002002', 'Trần Thị Bích',    '1998-07-22', 'FEMALE', '456 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201002002_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201002002_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201002002_selfie.jpg',");
            pw.printf( "    'CONFIRM', NULL, %s, 5, %s, %s),%n", now, now, now);

            pw.println("(3, '079201003003', 'Lê Quang Cường',   '1992-11-08', 'MALE',   '789 Trần Hưng Đạo, Phường 2, Quận 5, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201003003_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201003003_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201003003_selfie.jpg',");
            pw.printf( "    'CONFIRM', NULL, %s, 6, %s, %s),%n", now, now, now);

            pw.println("(4, '079201004004', 'Phạm Thị Dung',    '2000-01-30', 'FEMALE', '101 Nguyễn Trãi, Phường 3, Quận 5, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201004004_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201004004_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201004004_selfie.jpg',");
            pw.printf( "    'CONFIRM', NULL, %s, 7, %s, %s),%n", now, now, now);

            pw.println("(5, '079201005005', 'Hoàng Văn Em',     '1997-05-12', 'MALE',   '202 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201005005_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201005005_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201005005_selfie.jpg',");
            pw.printf( "    'PENDING', NULL, NULL, 8, %s, %s),%n", now, now);

            pw.println("(6, '079201006006', 'Đặng Thị Phương',  '1999-09-05', 'FEMALE', '303 Hai Bà Trưng, Phường Tân Định, Quận 1, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201006006_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201006006_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201006006_selfie.jpg',");
            pw.printf( "    'REJECT', 'Ảnh CCCD mặt trước bị mờ, không đọc được thông tin. Vui lòng chụp lại ảnh rõ nét hơn.', NULL, 9, %s, %s),%n", now, now);

            pw.println("(7, '079201007007', 'Võ Thị Giang',     '1996-12-18', 'FEMALE', '404 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP.HCM',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201007007_front.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201007007_back.jpg',");
            pw.println("    'https://res.cloudinary.com/rikkeibank/image/upload/kyc/079201007007_selfie.jpg',");
            pw.printf( "    'PENDING', NULL, NULL, 10, %s, %s);%n", now, now);
            pw.println();

            // ====== TRANSACTIONS ======
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- 5. TRANSACTIONS (15 giao dịch)");
            pw.println("-- ══════════════════════════════════════════");
            pw.println("INSERT INTO transactions (id, transaction_code, amount, description, status, type, from_account_id, to_account_id, created_at, updated_at) VALUES");
            pw.println("-- Ngày 25/06");
            pw.println("(1,  'TXN20260625001', 5000000.00,  'Chuyển tiền ăn trưa tháng 6',            'SUCCESS', 'INTERNAL', 4, 5, '2026-06-25 08:30:00', '2026-06-25 08:30:00'),");
            pw.println("(2,  'TXN20260625002', 12000000.00, 'Trả tiền mua laptop cũ',                 'SUCCESS', 'INTERNAL', 6, 4, '2026-06-25 10:45:00', '2026-06-25 10:45:00'),");
            pw.println("-- Ngày 26/06");
            pw.println("(3,  'TXN20260626001', 3500000.00,  'Cho mượn tiền đóng học phí',              'SUCCESS', 'INTERNAL', 4, 7, '2026-06-26 09:15:00', '2026-06-26 09:15:00'),");
            pw.println("(4,  'TXN20260626002', 1500000.00,  'Tiền góp quỹ team building',              'SUCCESS', 'INTERNAL', 5, 6, '2026-06-26 14:00:00', '2026-06-26 14:00:00'),");
            pw.println("-- Ngày 27/06");
            pw.println("(5,  'TXN20260627001', 2000000.00,  'Trả tiền vay tuần trước',                 'SUCCESS', 'INTERNAL', 7, 4, '2026-06-27 11:20:00', '2026-06-27 11:20:00'),");
            pw.println("(6,  'TXN20260627002', 8000000.00,  'Thanh toán tiền thuê nhà tháng 7',        'SUCCESS', 'INTERNAL', 4, 6, '2026-06-27 16:30:00', '2026-06-27 16:30:00'),");
            pw.println("-- Ngày 28/06");
            pw.println("(7,  'TXN20260628001', 4500000.00,  'Chuyển tiền mua vé máy bay đi Đà Nẵng',  'SUCCESS', 'INTERNAL', 6, 5, '2026-06-28 07:45:00', '2026-06-28 07:45:00'),");
            pw.println("(8,  'TXN20260628002', 750000.00,   'Tiền cà phê nhóm tuần này',               'SUCCESS', 'INTERNAL', 5, 7, '2026-06-28 09:00:00', '2026-06-28 09:00:00'),");
            pw.println("-- Ngày 29/06");
            pw.println("(9,  'TXN20260629001', 15000000.00, 'Đặt cọc mua xe máy Honda Wave',           'SUCCESS', 'INTERNAL', 4, 5, '2026-06-29 10:30:00', '2026-06-29 10:30:00'),");
            pw.println("(10, 'TXN20260629002', 6000000.00,  'Tiền học phí khóa tiếng Anh giao tiếp',   'SUCCESS', 'INTERNAL', 7, 6, '2026-06-29 14:15:00', '2026-06-29 14:15:00'),");
            pw.println("-- Ngày 30/06");
            pw.println("(11, 'TXN20260630001', 2500000.00,  'Hoàn tiền đặt cọc phòng trọ tháng 5',    'SUCCESS', 'INTERNAL', 6, 4, '2026-06-30 08:00:00', '2026-06-30 08:00:00'),");
            pw.println("(12, 'TXN20260630002', 10000000.00, 'Trả nợ tháng 6 - đợt cuối',               'SUCCESS', 'INTERNAL', 5, 4, '2026-06-30 15:30:00', '2026-06-30 15:30:00'),");
            pw.println("-- Hôm nay 01/07");
            pw.println("(13, 'TXN20260701001', 1000000.00,  'Mừng sinh nhật bạn Dung',                  'SUCCESS', 'INTERNAL', 4, 7, '2026-07-01 06:00:00', '2026-07-01 06:00:00'),");
            pw.println("(14, 'TXN20260701002', 50000000.00, 'Chuyển tiền lớn - SỐ DƯ KHÔNG ĐỦ',       'FAILED',  'INTERNAL', 7, 5, '2026-07-01 06:30:00', '2026-07-01 06:30:00'),");
            pw.println("(15, 'TXN20260701003', 3000000.00,  'Tiền ăn uống team cuối tuần',              'SUCCESS', 'INTERNAL', 4, 6, '2026-07-01 07:00:00', '2026-07-01 07:00:00');");
            pw.println();
            
            pw.println("-- Bật lại kiểm tra foreign key");
            pw.println("SET FOREIGN_KEY_CHECKS = 1;");
            pw.println();
            pw.println("-- ══════════════════════════════════════════");
            pw.println("-- ✅ SEED HOÀN TẤT! Kiểm tra dữ liệu:");
            pw.println("-- ══════════════════════════════════════════");
            pw.println("SELECT 'roles' AS tbl, COUNT(*) AS total FROM roles");
            pw.println("UNION ALL SELECT 'users', COUNT(*) FROM users");
            pw.println("UNION ALL SELECT 'accounts', COUNT(*) FROM accounts");
            pw.println("UNION ALL SELECT 'kyc_profiles', COUNT(*) FROM kyc_profiles");
            pw.println("UNION ALL SELECT 'transactions', COUNT(*) FROM transactions;");
        }
        
        System.out.println("════════════════════════════════════════════════════════════");
        System.out.println("  ✅ File SQL đã được tạo: " + filePath);
        System.out.println("════════════════════════════════════════════════════════════");
        System.out.println("  Password Hash: " + passwordHash);
        System.out.println("  PIN Hash:      " + pinHash);
        System.out.println();
        System.out.println("  Cách sử dụng:");
        System.out.println("    mysql -u root -p < docs/seed_data.sql");
        System.out.println("    hoặc copy nội dung vào MySQL Workbench/phpMyAdmin");
        System.out.println("════════════════════════════════════════════════════════════");
    }
}
